### Issue
Function in question is a Timer trigger written in Python 3.8, it triggers on schedule and works well without issue. 

However, when doing a Test/Run in the functions portal, a 500 internal server error would occur:
